# Generated by Django 5.0.2 on 2024-02-09 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=5)),
                ('discription', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profession')),
            ],
            options={
                'verbose_name': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='VisRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.people')),
            ],
            options={
                'verbose_name': 'Посещаемость',
            },
        ),
    ]
